name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.os}}
    strategy:
      max-parallel: 10
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-11]
        python-version: [3.8, 3.9, 3]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -v tests/


